### ISSUE TITLE
Изучить Markdown

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/itmo_lab_delivery_application#1]
Все будут писать readme.md к своим проектам, так что всем надо изучить, как их писать.

**Comment by gri-gri** [comment]
Я изучил, свою часть работы выполнил.

**Comment by gri-gri** [comment]
Как делаете свою часть issue - пишите, последний, кто сделает - закрывает issue, но могу закрыть и я, в принципе.

**Comment by Martakor1** [comment]
Ну и я сделал

**Comment by dobrmar** [comment]
+

**Comment by dobrmar** [comment]
/+

**Comment by dobrmar** [comment]
\+

**Comment by dobrmar** [comment]
о, вот теперь изучила

**Comment by schtschee** [comment]
Плюсик
