### ISSUE TITLE
Прочитать про создание реляционных баз данных

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/itmo_lab_delivery_application#25]
Ссылка от Fredi, вроде полезно, осилить стоит: https://towardsdatascience.com/designing-a-relational-database-and-creating-an-entity-relationship-diagram-89c1c19320b2

**Comment by gri-gri** [comment]
Нашёл великолепную статью на русском языке: https://habr.com/ru/post/535588/.

**Comment by gri-gri** [comment]
Я прочитал первую часть по ссылке от Fredi, но не очень понравилось, трудновато для понимания и примеров мало. А статья в моём комментарии хороша, как мне кажется.

**Comment by dobrmar** [comment]
done

**Comment by gri-gri** [comment]
@Martakor1 @schtschee Если хотите - прочитайте, будет полезно. Если не хотите, закройте issue и в доске передвиньте.

**Comment by gri-gri** [comment]
Всё, больше никто не хочет читать
