### ISSUE TITLE
Продумать архитектуру БД на бумаге

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/itmo_lab_delivery_application#29]
Ретроспектива.

**Comment by gri-gri** [comment]
Сделали!

**Comment by FrediKats** [comment]
@gri-gri а результаты её где?)

**Comment by dobrmar** [comment]
Вот^
(а вообще это переросло в #27, наверное, стоило здесь это указать упс)
![image](https://user-images.githubusercontent.com/45101245/141658209-9eb6a54f-b94d-4fd8-aae1-74614a227b69.png)
![image](https://user-images.githubusercontent.com/45101245/141658214-ce964774-8481-42e5-9a70-09e00e65dd57.png)
