### ISSUE TITLE
Изучить django или flask

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/itmo_lab_delivery_application#37]
Потыкать и выбрать что-то одно.

**Comment by Martakor1** [comment]
Выбрал django. Но решил начать с азов. Просмотрел что такое фреймворки, посмотрел как он работает, изучил схему общения клиента и сервера, прочитал ещё пачку статей по этой теме. Узнал, что у mdn есть прекрасные подробные статьи про django и про то, как на нём сделать сайт (очень подробно расписано). https://developer.mozilla.org/ru/docs/Learn/Server-side/Django - буду использовать эти материалы.
