### ISSUE TITLE
Написать класс DatabaseReader

### ISSUE THREAD

**Issue by gri-gri** [gri-gri/itmo_lab_delivery_application#42]
Написать методы для use-кейсов: проанализировать use-кейсы и для каждого написать методы получения инфы из двумерных списков.

**Comment by dobrmar** [comment]
Так как при обсуждении архитектуры БД мы временно забили на логин-пароль: что делать со сценариями создания аккаунта (aka авторизация)?
1. Пока забить на них
2. Добавить две БД (одна для преподов, одна для студентов) с логинами-паролями
3. Временно реализовать метод, который получает на вход только табельный номер (только надо притвориться, что у всех преподов они есть и при том не совпадают с учениками) и возвращает, существует ли человек с таким номером, и если да, является ли он студентом или преподом.

**Comment by dobrmar** [comment]
Мне кажется, для этой issue и #41 лучше сделать одну общую ветку.

**Comment by gri-gri** [comment]
Да не, не думаю, что нужна одна ветка. Я сейчас могу отправить на доделывание твой pull request, а сам пойду делать пример БД. Если мы начнём фигачить в одной ветке один и тот же файл... Будет не очень приятно
