### ISSUE TITLE
Исправить бд

### ISSUE THREAD

**Issue by dobrmar** [gri-gri/itmo_lab_delivery_application#54]
Добавить "comment" в таблицу лабосдач
Возможно, что-то еще (будет понятно после закрытия #41 и #42)

**Comment by gri-gri** [comment]
@dobrmar А может мы оценку для лабосдачи будем всё-таки в виде строки хранить? А то непонятно, какие ограничения ставить на цифры. Если да, то и дефолтное значения должно быть строкой, а не -1.

**Comment by dobrmar** [comment]
Окей. Дефолт тогда пустая строка? Или что-то вроде "не оценено", чтобы проверку не проводить
